### ISSUE TITLE
small mistake in Hypervolume.java

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#103] opened 2017-04-05 13:41 UTC
Hi, I found a small mistake in Hypervolume.java. (version 2.11, I don't know whether you correct this in the latest version)
 
		for (Solution solution : approximationSet) {
			//prune any solutions which exceed the Nadir point
			for (int i=0; i<solution.getNumberOfObjectives(); i++) {
				if (solution.getObjective(i) > 1.0) {
					continue;
				}
			}			
			Solution clone = solution.copy();					
			if (isInverted) {
				invert(problem, clone);
			}					
			solutions.add(clone);
		}

It  wants to prune any solutions which exceed the Nadir point, but the "continue" will jump to next objective of this solution, instead of jumping to next solution. In fact no solutions will be pruned. It can be corrected like this:

	for (Solution solution : approximationSet) {
			//prune any solutions which exceed the Nadir point
			
			boolean isin=true;
			for (int i=0; i<solution.getNumberOfObjectives(); i++) {
				if (solution.getObjective(i) > 1.0){
					isin=false;
					break;
				}
				
			}
			
			if (isin)
			{
				Solution clone = solution.copy();
						
				if (isInverted) {
					invert(problem, clone);
				}
						
				solutions.add(clone);
			}
		}

**Comment by dhadka** [comment] 2017-04-13 12:43
Thanks for reporting this.  The problem is fixed in 150b96857fda6cc99422cd0f04eacd9a039ea5d4.

**Closed** 2017-06-27 21:52 UTC
