### ISSUE TITLE
why the result of MOEAFRAMEWORK is very different with those on paper?

### ISSUE THREAD

**Issue by zhoudiprivateChina** [MOEAFramework/MOEAFramework#25] opened 2015-12-21 08:11 UTC
Hi, I download the moeaframework and run the Example2, but find out that the results obtained are not quite similar with those on the paper "Durillo, J. J., J. Garc�a-Nieto, A. J. Nebro, C. A. Coello Coello, F. Luna, and E. Alba (2009).  Multi-Objective Particle Swarm Optimizers: An Experimental Comparison.  Evolutionary Multi-Criterion Optimization, pp. 495-509. " For example, for OMOPSO on ZDT1, the AdditiveEpsilonIndicator achieved by MOEAFRAMEWORK is:
AdditiveEpsilonIndicator: 
        Min: 1.818785091698089
        Median: 2.0689157644607405
        Max: 2.3775349483731034
        Count: 50
        Indifferent: []

But the AdditiveEpsilonIndicator in that paper is 6.36e-3, the difference is very considerable.  However, I check the parameters of OMOPSO in moeaframework and those on that paper, it seems that they run with the same parameters. So, is there anything wrong? Thank you very much.

**Comment by zhoudiprivateChina** [comment] 2015-12-21 08:15
![image](https://cloud.githubusercontent.com/assets/16380025/11926202/d4503226-a7fd-11e5-890b-f789aa7f5bf1.png)
It's cut from the paper."Durillo, J. J., J. Garc�a-Nieto, A. J. Nebro, C. A. Coello Coello, F. Luna, and E. Alba (2009). Multi-Objective Particle Swarm Optimizers: An Experimental Comparison. Evolutionary Multi-Criterion Optimization, pp. 495-509. "

**Comment by dhadka** [comment] 2015-12-21 13:40
Hi, thanks for reporting this.  The number's you're seeing for Additive Epsilon Indicator are definitely off.  With the following code, I get numbers closer to the paper:

```java
public class Example2 {

	public static void main(String[] args) throws IOException {
		String problem = "ZDT1";
		String[] algorithms = { "OMOPSO" };
		
		//setup the experiment
		Executor executor = new Executor()
				.withProblem(problem)
				.withMaxEvaluations(25000);

		Analyzer analyzer = new Analyzer()
				.withProblem(problem)
				.includeAdditiveEpsilonIndicator()
				.showStatisticalSignificance();
		
		for (String algorithm : algorithms) {
			analyzer.addAll(algorithm, 
					executor.withAlgorithm(algorithm).runSeeds(50));
		}

		//print the results
		analyzer.printAnalysis();
	}
	
}
```

which produces the output:

```
OMOPSO:
    AdditiveEpsilonIndicator: 
        Min: 0.008928880357692015
        Median: 0.009665457659340043
        Max: 0.011832467183914674
        Count: 50
        Indifferent: []
```

These numbers differ slightly from the paper you cited.  This is caused by a discrepancy between the OMOPSO algorithm as described in the paper and the original author's implementation.  In the paper by Sierra and Coello Coello, "Improving PSO-based Multi-Objective Optimization using Crowding Distance, Mutation, and epsilon-Dominance", their algorithm is supposed to return the epsilon-dominance archive (see Fig 1).  The paper you cited using JMetal.  JMetal's implementation returns the leaders and not the epsilon-dominance archive.  This is what is causing the difference in performance.

If you would like to replicate the results from JMetal, you have two options.  For Option 1, edit AbstractPSOAlgorithm.java and set `TESTING_MODE` to `true`:

```java
	/**
	 * The original implementation of OMOPSO in JMetal returns the leaders
	 * instead of the epsilon-dominance archive as described in the literature.
	 * This results in a small performance difference that is detected by our
	 * unit tests.  To enable unit testing to compare the two implementations,
	 * this flag forces OMOPSO to behave like the JMetal implementation and
	 * only return the leaders.
	 */
	static boolean TESTING_MODE = true;
```

For Option 2, you can run JMetal's implementation directly.  Simply use the algorithm "OMOPSO-JMetal":

```java
	public static void main(String[] args) throws IOException {
		String problem = "ZDT1";
		String[] algorithms = { "OMOPSO-JMetal" };
		
		//setup the experiment
		Executor executor = new Executor()
				.withProblem(problem)
				.withMaxEvaluations(25000);

		Analyzer analyzer = new Analyzer()
				.withProblem(problem)
				.includeAdditiveEpsilonIndicator()
				.showStatisticalSignificance();
		
		for (String algorithm : algorithms) {
			analyzer.addAll(algorithm, 
					executor.withAlgorithm(algorithm).runSeeds(50));
		}

		//print the results
		analyzer.printAnalysis();
	}
```

With either option, you'll then see results similar to:

```
OMOPSO-JMetal:
    AdditiveEpsilonIndicator: 
        Min: 0.005458843784323986
        Median: 0.006200919245953174
        Max: 0.007325059248649577
        Count: 50
        Indifferent: []
```

**Comment by zhoudiprivateChina** [comment] 2015-12-23 08:03
Hi, thanks for the detailed explanation, And I have the new question, :)  I check the code in AbstractPSOAlgorithm.java, notice the velocity update part is written as:
protected void updateVelocity(int i) {
		Solution particle = particles[i];
		Solution localBestParticle = localBestParticles[i];
		Solution leader = selectLeader();
		................
			velocities[i][j] = W * velocities[i][j] + 
					C1*r1*(localBestValue - particleValue) +
					C2*r2*(leaderValue - particleValue);
		}
	} 

When i change the velocity update equation as: 
velocities[i][j] = C1*r1*(localBestValue - particleValue) +
					C2*r2*(leaderValue - particleValue);
the results seems very similar with those obtained by original algorithm. For example, using the new velocities equation,the results of OMOPSO on ZDT1:
OMOPSO:
    InvertedGenerationalDistance: 
        Min: 0.005138340262563539
        Median: 0.0051744740098407715
        Max: 0.005779374657696546
        Count: 50
        Indifferent: []
    AdditiveEpsilonIndicator: 
        Min: 0.00931718710786339
        Median: 0.009701686041551518
        Max: 0.011540342959743266
        Count: 50
        Indifferent: []

It's very unreasonable. what do u think?

**Comment by zhoudiprivateChina** [comment] 2015-12-23 08:29
hey,it' me again. It's really odd and i consider it for a long time. I make a test, and find out that if i change the velocity update equation as: velocities[i][j] = C2*r2*(leaderValue - particleValue); OR velocities[i][j] = C2*r2*(leaderValue - particleValue)+C1*r1*(localBestValue - particleValue) ;   the results are really similar with the original ones. Only when i change the equation as velocities[i][j] = C1*r1*(localBestValue - particleValue) ;  the results then differ a lot.  Is that a bug or the problem in PSO?

**Comment by dhadka** [comment] 2015-12-23 09:02
Looking at a runtime plot of the algorithms with different velocity update equations, there are definitely differences.  The top figure is from `velocities[i][j] = C2r2(leaderValue - particleValue);` and the bottom figure is the original equation.

![img1](https://cloud.githubusercontent.com/assets/2496211/11973439/3654847e-a928-11e5-9945-0143f1757f4f.png)
![img2](https://cloud.githubusercontent.com/assets/2496211/11973441/37dd44b6-a928-11e5-92f6-9ae15176bfa4.png)

Thus, while the two equations produce nearly identical results at the end of the run with 25000 evaluations, they differ more throughout the run.

I think the update equation `velocities[i][j] = C1r1(localBestValue - particleValue);` doesn't work because at initialization the velocities are 0 and localBestValue == particleValue.  Thus, there is no change.

The update equation for OMOPSO is designed to have an inertia component, `W * velocities[i][j]`, a component driving particles towards the Pareto front, `C1r1(localBestValue - particleValue)`, and a component increasing diversity, `C2r2(leaderValue - particleValue)`.

**Comment by zhoudiprivateChina** [comment] 2015-12-30 08:32
Hi again. I'm still working on that odd problem, and in my opinion, although they are different in the convergence in the running time, but it's still very unreasonable that they got the similar results no matter measured in Spacing, Hypervolume, or AdditiveEpsilonIndicator. BTW, The default charts in the diagnostic tool show the statistical 25%, 50%, 75%quantiles, but how to plot the line demonstrated the average of all running rounds?

**Comment by dhadka** [comment] 2016-01-04 15:35
Currently, the diagnostic tool doesn't support plotting the average.  You can enable this by editing `src/org/moeaframework/analysis/diagnostics/LinePlot.java` and replace the text (line 193):

```java

					series.add(currentNFE, 
							statistics.getPercentile(50), 
							statistics.getPercentile(25), 
							statistics.getPercentile(75));
```

with

```java

					series.add(currentNFE, 
							statistics.getMean(),
							statistics.getMin(),
							statistics.getMax());
```

You could also try making the same changes to [JMetal's](http://jmetal.sourceforge.net/) OMOPSO implementation to see if the result is the same.  If you do spot a bug, please let us know!

**Comment by dhadka** [comment] 2016-02-18 21:55
Closing this ticket.  Please open a new one if you have other questions.

**Closed by dhadka** 2016-02-18 21:55 UTC
