### ISSUE TITLE
WindowBuilder was not able to show the GUI of Diagnostic Tool

### ISSUE THREAD

**Issue by longmeili** [MOEAFramework/MOEAFramework#17] opened 2015-11-06 15:24 UTC
![image](https://cloud.githubusercontent.com/assets/15227853/11000429/05f20c66-84a2-11e5-9325-575199253379.png)
Hi, I am trying to look at the design of Diagnostic Tool.java, but it cannot be opened.Look at the picture for detail. Besides, there are many warnings says "JComboBox is a raw type""JList is a raw type", it seems JComboBox and JList are not recognised.

**Comment by dhadka** [comment] 2015-11-06 19:08
The Diagnostic Tool GUI was designed without WindowBuilder, so it's unfortunately not compatible.  You should instead right-click the file and select Open With > Java Editor to view the underlying Java code.

The warnings are caused by newer versions of Java (7+) allowing parameterized types (generics) in some Swing components.  We are intentionally not using generics in Swing components for backwards compatibility, resulting in the warnings you see.

**Comment by longmeili** [comment] 2015-11-07 18:45
Thanks a lot

2015-11-06 20:08 GMT+01:00 David Hadka <notifications@github.com>:

**Comment by dhadka** [comment] 2015-11-09 16:09
Closing ticket.  Please open a new ticket if you have any other questions.

**Closed by dhadka** 2015-11-09 16:09 UTC
