### ISSUE TITLE
NondominatedSortingPopulation/NondominatedPopulation

### ISSUE THREAD

**Issue by Nozo** [MOEAFramework/MOEAFramework#20] opened 2015-11-18 13:43 UTC
I have a NondominatedSortingPopulation and want to convert the solutions into a NondominatedPopulation to calculate some metrics with a maximal amount of 100 non dominated solutions. I do not expect to receive a different amount of  non dominated solutions in both cases illustrated below. I know that the NondominatedSortingComparator uses the   NondominatedSortingComparator which consist of the Ranking- and CrowdingComparator. And the NondominatedPopulation uses the  ParetoDominanceComparator. In case 2 the NondominatedSortingComparator finds less non dominated solutions then the ParetoObjectiveComparator that's a little bit confusing for me because if I don't change any comparator and use the default ones this should be the same in the end. 
(Changing the duplicate mode in the NondominatedPopulation do not change the result)

the numbers are the population size:

Case 1:

 NondominatedSortingPopulation   200  -->addAll to NondominatedPopulation  108 remain --> truncate(100, Crowding) --> 100

Case2:

 NondominatedSortingPopulation   200  --> truncate(100)  --> addAll to NondominatedPopulation  80 remain

**Comment by dhadka** [comment] 2015-11-18 13:59
Can you please upload the starting population?  You can save it using:

    PopulationIO.write(new File("population.dat"), population);

**Comment by Nozo** [comment] 2015-11-18 14:32
At the moment I am at the wrong pc but I don't know if the starting population is very helpful, because the solutions are created via an island parallelization with migration from between the different islands. For this test I used your RandomInitialization  Object for a discrete integer problem with values from 1 to 5 and 10 decision variables.

**Comment by dhadka** [comment] 2015-11-18 16:02
This may or may not be the cause of what you're seeing, but in some tests I found that the existence of duplicate solutions in the NondominatedSortingPopulation can lead to the behavior you're reporting.  What happens is the following:

1. The NondominatedSortingPopulation has duplicate solutions
2. During fast non-dominated sorting, the duplicate solutions are given the same rank
3. When assigning the crowding distance, if the duplicate solution lies at the extreme value of more than one objective then there's a chance that more than one duplicate solution is given a crowding distance of infinity
4. If N is the # of rank 0 solutions, when truncating to a size k < N, then more than one of the duplicate solutions will be kept since more than one has a crowding distance of infinity.  This causes other non-dominated solutions, which have a crowding distance < infinity, to be removed instead
5. Then, when adding the truncated set to a NondominatedPopulation, the duplicate solutions are removed resulting in a smaller set

This appears to be an edge case that primarily occurs when using discrete representations, since it's very unlikely to generate two duplicate real values.  The following potential fix ignores duplicate solutions within each front and assigns them a crowding distance of 0.0:

```java
	public void updateCrowdingDistance(Population front) {
		int n = front.size();

		if (n < 3) {
			for (Solution solution : front) {
				solution.setAttribute(CROWDING_ATTRIBUTE,
						Double.POSITIVE_INFINITY);
			}
		} else {
			int numberOfObjectives = front.get(0).getNumberOfObjectives();

			for (Solution solution : front) {
				solution.setAttribute(CROWDING_ATTRIBUTE, 0.0);
			}
			
			// remove any duplicate solutions
			NondominatedPopulation uniqueFront = new NondominatedPopulation(
					DuplicateMode.NO_DUPLICATES);
			uniqueFront.addAll(front);
			front = uniqueFront;
			n = front.size();

			for (int i = 0; i < numberOfObjectives; i++) {
				front.sort(new ObjectiveComparator(i));

				double minObjective = front.get(0).getObjective(i);
				double maxObjective = front.get(n - 1).getObjective(i);

				front.get(0).setAttribute(CROWDING_ATTRIBUTE,
						Double.POSITIVE_INFINITY);
				front.get(n - 1).setAttribute(CROWDING_ATTRIBUTE,
						Double.POSITIVE_INFINITY);

				for (int j = 1; j < n - 1; j++) {
					double distance = (Double)front.get(j).getAttribute(
							CROWDING_ATTRIBUTE);
					distance += (front.get(j + 1).getObjective(i) - 
							front.get(j - 1).getObjective(i))
							/ (maxObjective - minObjective);
					front.get(j).setAttribute(CROWDING_ATTRIBUTE, distance);
				}
			}
		}
	}
```

**Comment by dhadka** [comment] 2015-11-18 16:07
As a longer-term solution, I'll probably modify the ranking procedure to mark duplicate solutions so that they can be efficiently ignored rather than having to perform dominance checks a second time.

**Comment by Nozo** [comment] 2015-11-18 16:13
Like always very quick and helpful response!
Especially point 3 was completely out of my sight!
Thank you very much!

**Comment by dhadka** [comment] 2015-11-18 20:22
Committed a fix to branch fix_issue_15.  Please try it out and see if it resolves the issue.

**Comment by Nozo** [comment] 2015-11-19 11:40
Now both cases the same amount of non dominated solutions are stored in the non dominated population (The amount of found non dominated solutions is also increased)
The Problem is that the required time for one NSGAII iteration in my design is increased from 1,3ms to 20,0ms for a population size of 100 (just by changing the MOEA-Framework jar file) this is huge and so I have to use the old NondominatedSorting Population with the FastNondominatedSorting which is not derived from NondominatedSorting. Is it possible to speed the new FastNondominatedSorting  up?

**Comment by dhadka** [comment] 2015-11-19 13:50
Please update and try again.  I made two changes:

1. Defaults to use the old nondominated sorting, which tends to be faster in practice
2. Reduce the number of checks needed to determine if a solution is a duplicate (this should help make `FastNondominatedSorting` faster)

**Comment by Nozo** [comment] 2015-11-19 14:48
I make some fast tests:
The Iteration time with the new Framework version is about 10,0 ms, lets say a factor of 5 slower then the MOEA 2.6 version. 

Iteration Time: 1634 us     without any changes to the Sorting (No Dublicate handling in NDSP*)
Migration: 510 Time  us

Iteration Time: 22641 us    with the Sorting changes without performance improvements 
Migration Time: 6134 us

Iteration Time:  9648 us    with the Sorting changes and performance improvements 
Migration Time: 6050 us

*NDSP = NondominatetSortingPopulation

**Comment by Nozo** [comment] 2015-11-24 08:18
Is it possible adding a duplicate mode for the NondominatedSortingPopulation like you do it for the NondominatedPopulation? Our Test problem is not completely to solve with the actual implementation because half of our rank1 Solutions have the same fitness values but different decision variables. the NondominatedsortingPopulation treats them as copies. In some cases we want to have a result with a fixed amount of solutions. If this number of solutions is higher then the number of found nondominated solutions it is completely filled with copy's. Other relatively good rank1 or 2 solutions are displaced by the copy's of rank 0 but this copy's providing no additional informations.

**Comment by Nozo** [comment] 2015-11-24 09:30
I do some further tests and it seems like I receive way better results (number of non dominated solutions and better performance) by removing the duplicate handling and just changing the Duplicate_Mode to Allow_Duplicate_Objectives for the NondominatedPopulation in the FastNondominatedSorting! So I discard your last changes going back to the version before your last commit with the changes to the NondominatedPopulation and just changing the Allow_Duplicate_Objectives option in the FastNondominatedSorting. Otherwise we have the problem the our fixed sized end population is floated with rank 0 duplicates with same decision variables instead of rank 1 solutions with new/additional information. And we only want to have duplicates in our final population with different decision variables. For some multiobjective problems the duplicates may help to converge faster to the optimal pareto front but not for all problems.

**Comment by dhadka** [comment] 2016-01-07 13:21
Thanks for taking the time to test, closing this ticket.

**Closed by dhadka** 2016-01-07 13:21 UTC
